@startuml
start
:FE:user click log in;
:BE:generate id by timeStamp
and save it in ctx.session
and global.mySessionStore
redirect to /list
;
:BE: /list response {
    username,
    id,
    msgs
};
:FE: make sure the user's been logged in
emit {{id}};
:BE: match to FE's emit
save the socketid in mySessionStore;
:FE:click send emit sendMsg {content};
:BE:match to FE's emit,find the obj whose socketid is xxx
and broadcast the content;
stop
@enduml